const mongoose = require('mongoose');
const generatePickupCode = require('../utils/generatePickupCode');

const orderItemSchema = new mongoose.Schema(
  {
    product: { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true },
    itemName: { type: String, required: true },
    unitPrice: { type: Number, required: true },
    quantity: { type: Number, required: true, min: 1 },
    fromBatch: { type: String, enum: ['current', 'next'], default: 'current' },
  },
  { _id: false }
);

const orderSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    vendor: { type: mongoose.Schema.Types.ObjectId, ref: 'VendorProfile', required: true },
    items: { type: [orderItemSchema], required: true, validate: (v) => v.length > 0 },

    orderType: { type: String, enum: ['Direct', 'Prebook'], required: true },
    fulfillmentMethod: { type: String, enum: ['Delivery', 'Takeaway'], required: true },
    scheduledFor: { type: Date, default: null }, // required for Prebook orders

    // Set when this order was auto-generated by a daily subscription run
    // rather than placed directly by the customer (see CustomerSubscription).
    subscription: { type: mongoose.Schema.Types.ObjectId, ref: 'CustomerSubscription', default: null },

    deliveryAddress: {
      coordinates: { type: [Number], default: undefined },
      address: { type: String, default: '' },
    },

    itemsTotal: { type: Number, required: true, min: 0 },
    deliveryFee: { type: Number, required: true, default: 0, min: 0 },
    totalAmount: { type: Number, required: true, min: 0 },

    // What the platform actually takes and what's owed back to the vendor —
    // recorded per order so commission is auditable/reportable rather than
    // computed after the fact from vendor tier alone.
    platformCommissionRate: { type: Number, default: 0 },
    platformCommissionAmount: { type: Number, default: 0 },
    vendorPayoutAmount: { type: Number, default: 0 },

    // Estimated cost of the delivery leg paid out to a logistics
    // partner/gig-worker — distinct from `deliveryFee`, which is what the
    // customer is charged. Lets profitability be assessed per delivery order
    // instead of assuming the customer fee covers the actual courier cost.
    deliveryCostToProvider: { type: Number, default: 0 },
    deliveryProviderRef: { type: String, default: '' },

    paymentStatus: {
      type: String,
      enum: ['pending', 'paid', 'failed', 'refunded'],
      default: 'pending',
    },
    gatewayOrderId: { type: String, default: '' },
    paymentId: { type: String, default: '' },

    status: {
      type: String,
      enum: ['Pending', 'Accepted', 'Preparing', 'Ready', 'OutForDelivery', 'Completed', 'Cancelled', 'Rejected'],
      default: 'Pending',
    },
    statusHistory: [
      {
        status: String,
        at: { type: Date, default: Date.now },
      },
    ],

    rating: { type: Number, min: 1, max: 5, default: null },
    ratingComment: { type: String, default: '' },

    // Shown to the customer as a QR code; the vendor scans (or manually
    // enters) it at handoff to confirm pickup/delivery and mark the order
    // Completed, instead of relying on an honesty-based status button.
    pickupCode: { type: String, required: true, default: generatePickupCode },
    pickupConfirmedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

orderSchema.index({ vendor: 1, status: 1, createdAt: -1 });
orderSchema.index({ user: 1, createdAt: -1 });
orderSchema.index({ vendor: 1, pickupCode: 1 });

orderSchema.pre('save', function pushHistory(next) {
  if (this.isModified('status') || this.isNew) {
    this.statusHistory.push({ status: this.status, at: new Date() });
  }
  next();
});

module.exports = mongoose.model('Order', orderSchema);
